/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'published' : boolean,
  'author' : string,
  'message' : string,
  'timestamp' : Time,
}
export type ContentCollection = { 'siteSettings' : null } |
  { 'staff' : null } |
  { 'events' : null } |
  { 'announcements' : null } |
  { 'gallery' : null };
export interface ContentMetadata {
  'id' : string,
  'contentType' : ContentCollection,
  'lastModified' : Time,
  'collectionUpdated' : Time,
  'collectionSize' : bigint,
}
export interface Event {
  'id' : string,
  'title' : string,
  'date' : bigint,
  'published' : boolean,
  'description' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface Setting { 'id' : string, 'key' : string, 'value' : string }
export interface StaffProfile {
  'id' : string,
  'bio' : string,
  'contact' : string,
  'published' : boolean,
  'name' : string,
  'position' : string,
  'photoId' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteSetting' : ActorMethod<[string], undefined>,
  'deleteStaffProfile' : ActorMethod<[string], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllPublishedStaff' : ActorMethod<[], Array<StaffProfile>>,
  'getAllSettings' : ActorMethod<[], Array<Setting>>,
  'getAnnouncement' : ActorMethod<[string], Announcement>,
  'getAnnouncementsByPublished' : ActorMethod<[boolean], Array<Announcement>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentMetadata' : ActorMethod<
    [ContentCollection, [] | [string]],
    [] | [ContentMetadata]
  >,
  'getEvent' : ActorMethod<[string], Event>,
  'getPublishedGalleryEntries' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getSetting' : ActorMethod<[string], [] | [Setting]>,
  'getStaffProfile' : ActorMethod<[string], StaffProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishFiles' : ActorMethod<[Array<string>], undefined>,
  'saveAnnouncement' : ActorMethod<[Announcement], undefined>,
  'saveEvent' : ActorMethod<[Event], undefined>,
  'saveSetting' : ActorMethod<[Setting], undefined>,
  'saveStaffProfile' : ActorMethod<[StaffProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];