/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int64,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const StaffProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'contact' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'position' : IDL.Text,
  'photoId' : IDL.Opt(IDL.Text),
});
export const Setting = IDL.Record({
  'id' : IDL.Text,
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const ContentCollection = IDL.Variant({
  'siteSettings' : IDL.Null,
  'staff' : IDL.Null,
  'events' : IDL.Null,
  'announcements' : IDL.Null,
  'gallery' : IDL.Null,
});
export const ContentMetadata = IDL.Record({
  'id' : IDL.Text,
  'contentType' : ContentCollection,
  'lastModified' : Time,
  'collectionUpdated' : Time,
  'collectionSize' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapFirstAdmin' : IDL.Func([], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteSetting' : IDL.Func([IDL.Text], [], []),
  'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllPublishedStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
  'getAnnouncementsByPublished' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getCallerPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentMetadata' : IDL.Func(
      [ContentCollection, IDL.Opt(IDL.Text)],
      [IDL.Opt(ContentMetadata)],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getFirstAdminWindowOpen' : IDL.Func([], [IDL.Bool], ['query']),
  'getPublishedGalleryEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
  'getStaffProfile' : IDL.Func([IDL.Text], [StaffProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveAnnouncement' : IDL.Func([Announcement], [], []),
  'saveEvent' : IDL.Func([Event], [], []),
  'saveSetting' : IDL.Func([Setting], [], []),
  'saveStaffProfile' : IDL.Func([StaffProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int64,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const StaffProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'contact' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'position' : IDL.Text,
    'photoId' : IDL.Opt(IDL.Text),
  });
  const Setting = IDL.Record({
    'id' : IDL.Text,
    'key' : IDL.Text,
    'value' : IDL.Text,
  });
  const ContentCollection = IDL.Variant({
    'siteSettings' : IDL.Null,
    'staff' : IDL.Null,
    'events' : IDL.Null,
    'announcements' : IDL.Null,
    'gallery' : IDL.Null,
  });
  const ContentMetadata = IDL.Record({
    'id' : IDL.Text,
    'contentType' : ContentCollection,
    'lastModified' : Time,
    'collectionUpdated' : Time,
    'collectionSize' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapFirstAdmin' : IDL.Func([], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteSetting' : IDL.Func([IDL.Text], [], []),
    'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllPublishedStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
    'getAnnouncementsByPublished' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCallerPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentMetadata' : IDL.Func(
        [ContentCollection, IDL.Opt(IDL.Text)],
        [IDL.Opt(ContentMetadata)],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getFirstAdminWindowOpen' : IDL.Func([], [IDL.Bool], ['query']),
    'getPublishedGalleryEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
    'getStaffProfile' : IDL.Func([IDL.Text], [StaffProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveAnnouncement' : IDL.Func([Announcement], [], []),
    'saveEvent' : IDL.Func([Event], [], []),
    'saveSetting' : IDL.Func([Setting], [], []),
    'saveStaffProfile' : IDL.Func([StaffProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };